// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCfM9HW40C2xNC_23llITXc_BQWtH-yyAQ',
    appId: '1:577579882957:web:fc7e56f9aeaeb2af9f4c84',
    messagingSenderId: '577579882957',
    projectId: 'heart-rate-app-fcd3b',
    authDomain: 'heart-rate-app-fcd3b.firebaseapp.com',
    storageBucket: 'heart-rate-app-fcd3b.firebasestorage.app',
    measurementId: 'G-M2Y892E5ZR',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDLnNRDo-ZKqdiUe6tVBbDNxi68UiqHT14',
    appId: '1:577579882957:android:a774c15d14b037a29f4c84',
    messagingSenderId: '577579882957',
    projectId: 'heart-rate-app-fcd3b',
    storageBucket: 'heart-rate-app-fcd3b.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCRUT9aqmnrE9hn30XMrWeRM62O_hhI_V4',
    appId: '1:577579882957:ios:23bd3596f292da039f4c84',
    messagingSenderId: '577579882957',
    projectId: 'heart-rate-app-fcd3b',
    storageBucket: 'heart-rate-app-fcd3b.firebasestorage.app',
    iosClientId: '577579882957-5eldiv2k19bpipfgesbgh1p23j83pinq.apps.googleusercontent.com',
    iosBundleId: 'com.example.flutterHeartrate',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCRUT9aqmnrE9hn30XMrWeRM62O_hhI_V4',
    appId: '1:577579882957:ios:23bd3596f292da039f4c84',
    messagingSenderId: '577579882957',
    projectId: 'heart-rate-app-fcd3b',
    storageBucket: 'heart-rate-app-fcd3b.firebasestorage.app',
    iosClientId: '577579882957-5eldiv2k19bpipfgesbgh1p23j83pinq.apps.googleusercontent.com',
    iosBundleId: 'com.example.flutterHeartrate',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCfM9HW40C2xNC_23llITXc_BQWtH-yyAQ',
    appId: '1:577579882957:web:318805b799aa9d629f4c84',
    messagingSenderId: '577579882957',
    projectId: 'heart-rate-app-fcd3b',
    authDomain: 'heart-rate-app-fcd3b.firebaseapp.com',
    storageBucket: 'heart-rate-app-fcd3b.firebasestorage.app',
    measurementId: 'G-D8Q5GZJMF8',
  );
}
